#!/bin/bash
set -e

# Installing yarn
YARN_VERSION="0.27.5"
YARN_LOCATION="tools/${YARN_VERSION}"

if [ ! -d "$YARN_LOCATION" ]; then
	mkdir -p ${YARN_LOCATION}
	pushd ${YARN_LOCATION}/
	wget -qO- https://github.com/yarnpkg/yarn/releases/download/v${YARN_VERSION}/yarn-v${YARN_VERSION}.tar.gz | tar zvx
	popd
fi

# Installing packages via yarn
pushd cloud-formation/src

../../${YARN_LOCATION}/dist/bin/yarn install

#Build CloudFormation
../../${YARN_LOCATION}/dist/bin/yarn run build-cfn

popd

# build scala
cd ..
./sbt "project support-workers" it:assembly \
"project support-workers" test riffRaffUpload \
"project it-test-runner" riffRaffUpload \
"project support-redemptiondb" riffRaffUpload
