package com.gu.support.promotions.dynamo

object Fixtures {
  val startDate = "2018-10-03T00:00:00.000+01:00"
  val promotion =
    s"""
    {
      "codes": {
          "House UK": [
              "WWM52X"
          ],
          "HEADER LINK GU.COM": [
              "WWM99X"
          ],
          "Paid Search": [
              "WWM41X"
          ],
          "Paid Social": [
              "WWM43X"
          ],
          "House AU": [
              "WWM52C"
          ],
          "House US": [
              "WWM52A"
          ],
          "YouTube": [
              "WWM88X"
          ],
          "PRESS": [
              "WWM24P"
          ],
          "Merchandising US": [
              "WWM51A"
          ],
          "Email Acquisition": [
              "WWM31X"
          ],
          "Organic Social": [
              "WWM62X"
          ],
          "Merchandising UK": [
              "WWM51X"
          ],
          "INSERT": [
              "WWM22F"
          ],
          "Merchandising AU": [
              "WWM51C"
          ],
          "On-Platform Editorial": [
              "WWM53X"
          ],
          "RETENTION ED EMAIL": [
              "WWM25X"
          ],
          "Display": [
              "WWM42X"
          ]
      },
      "promotionType": {
          "name": "tracking"
      },
      "expires": "2022-04-30T23:59:59.000+01:00",
      "name": "Subscribe to the Guardian Weekly",
      "appliesTo": {
          "productRatePlanIds": [
              "2c92a0086619bf8901661aaac94257fe",
              "2c92a0086619bf8901661ab545f51b21"
          ],
          "countries": [
              "SH",
              "IO",
              "GP",
              "VA",
              "KE",
              "MM",
              "TL",
              "LV",
              "GL",
              "MV",
              "GT",
              "GM",
              "GW",
              "BT",
              "SL",
              "AO",
              "RU",
              "MQ",
              "VU",
              "GQ",
              "PL",
              "BG",
              "MR",
              "AW",
              "TJ",
              "CK",
              "EC",
              "BJ",
              "KW",
              "UA",
              "FK",
              "PS",
              "BH",
              "AL",
              "AI",
              "TM",
              "BM",
              "ER",
              "SB",
              "SM",
              "SO",
              "PR",
              "SI",
              "QA",
              "PT",
              "WS",
              "BL",
              "PF",
              "JO",
              "HK",
              "NA",
              "MZ",
              "AS",
              "ET",
              "KG",
              "BQ",
              "GG",
              "LI",
              "US",
              "SG",
              "CY",
              "MX",
              "LA",
              "KY",
              "SR",
              "BE",
              "DZ",
              "TK",
              "HR",
              "AT",
              "MC",
              "BN",
              "PK",
              "BS",
              "IS",
              "BZ",
              "CR",
              "LT",
              "NZ",
              "SZ",
              "LR",
              "CW",
              "CL",
              "RE",
              "RW",
              "CN",
              "NF",
              "CZ",
              "EH",
              "PG",
              "IT",
              "MF",
              "TR",
              "YT",
              "KR",
              "TN",
              "MA",
              "NL",
              "JM",
              "MP",
              "IR",
              "AQ",
              "HM",
              "UM",
              "MH",
              "FO",
              "CD",
              "BY",
              "ZA",
              "TO",
              "SY",
              "IN",
              "TD",
              "DK",
              "CM",
              "DM",
              "CX",
              "SK",
              "BV",
              "BW",
              "ES",
              "EG",
              "AG",
              "TH",
              "MD",
              "OM",
              "VC",
              "SA",
              "CI",
              "CO",
              "AD",
              "TF",
              "KH",
              "SN",
              "PM",
              "CF",
              "NE",
              "PN",
              "CU",
              "FM",
              "HT",
              "TZ",
              "VE",
              "MO",
              "BF",
              "CA",
              "MG",
              "ME",
              "BD",
              "CG",
              "JE",
              "MY",
              "TG",
              "BA",
              "HU",
              "KI",
              "UZ",
              "MW",
              "FR",
              "AZ",
              "PW",
              "KP",
              "BO",
              "ST",
              "SS",
              "IM",
              "AF",
              "BB",
              "KZ",
              "MT",
              "IL",
              "MS",
              "PH",
              "LK",
              "DJ",
              "SC",
              "DO",
              "YE",
              "ZW",
              "VG",
              "GI",
              "LY",
              "TC",
              "SJ",
              "IE",
              "CV",
              "KN",
              "DE",
              "FI",
              "GN",
              "IQ",
              "GA",
              "JP",
              "AR",
              "PE",
              "FJ",
              "TW",
              "GS",
              "GE",
              "HN",
              "UG",
              "LB",
              "ML",
              "RS",
              "BR",
              "GR",
              "GU",
              "CC",
              "NU",
              "VI",
              "GH",
              "BI",
              "GF",
              "TV",
              "AE",
              "GY",
              "GB",
              "EE",
              "ID",
              "LS",
              "PA",
              "WF",
              "CH",
              "PY",
              "ZM",
              "GD",
              "LU",
              "SV",
              "UY",
              "AM",
              "NP",
              "KM",
              "MN",
              "TT",
              "NR",
              "RO",
              "LC",
              "MK",
              "NO",
              "SE",
              "SD",
              "AX",
              "AU",
              "VN",
              "NC",
              "NI",
              "MU",
              "SX",
              "NG"
          ]
      },
      "description": "Subscribe to the Guardian Weekly",
      "starts": "$startDate",
      "uuid": "ad94567b-799c-4374-8426-328f9f6178d0",
      "campaignCode": "C_JMQ4GUGL"
    }
  """
}
