#!/bin/bash

# Installing yarn
YARN_VERSION="0.23.2"

mkdir -p tools
cd tools/
wget https://github.com/yarnpkg/yarn/releases/download/v${YARN_VERSION}/yarn-v${YARN_VERSION}.tar.gz
tar zvxf yarn-v${YARN_VERSION}.tar.gz
cd ..

# Installing packages via yarn

tools/dist/bin/yarn install

# Building the client-side assets

tools/dist/bin/yarn run build-prod

