packages:
  - 'support-frontend'
  - 'cdk'
  - 'support-lambdas/bigquery-acquisitions-publisher'
  - 'support-e2e'
  - 'support-workers'
  - 'modules'
onlyBuiltDependencies:
  - "@guardian/support-service-lambdas"
catalog:
  typescript: ^5.2.2
  zod: ^3.23.8
  prettier: ^2.8.8
  jest: ^29.2.4
  jest-runner-groups: ^2.2.0
  ts-jest: ^29.2.4
  esbuild: ^0.25.5
  "@types/jest": ^29.5.12
  "@types/node": ^20.11.27
  "@aws-sdk/client-cloudwatch": ^3.995.0
  "@aws-sdk/client-eventbridge": ^3.995.0
  "@aws-sdk/client-sqs": ^3.995.0
  "@aws-sdk/client-ssm": ^3.995.0
  "@aws-sdk/client-secrets-manager": ^3.995.0
  "@aws-sdk/credential-provider-node": 3.972.10
  "@aws-sdk/client-dynamodb": ^3.995.0
  "@aws-sdk/util-dynamodb": ^3.995.0
  "@guardian/prettier": ^2.1.5
  "@guardian/support-service-lambdas": "guardian/support-service-lambdas#5d26271554a063133552d9d3b97a2e1357e9d735"
