packages:
  - 'support-frontend'
  - 'cdk'
  - 'support-lambdas/bigquery-acquisitions-publisher'
  - 'support-e2e'
  - 'support-workers'
catalog:
  zod: ^3.23.8
  eslint: ^8.57.0
  prettier: ^2.8.8
  jest: ^29.7.0
