export type StripeCardState = {
	formComplete: boolean;
	// The client secret is generated during the checkout process and is used to actually complete the payment
	setupIntentClientSecret?: string;
	// The payment method is a token generated by Stripe that allows us to later retrieve the money
	stripePaymentMethod?: string;
};

export const initialStripeCardState: StripeCardState = {
	formComplete: false,
};
