AWSTemplateFormatVersion: 2010-09-09
Description: support-frontend-static
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: support-frontend-static
      MetricsConfigurations:
        - Id: EntireBucket
      LifecycleConfiguration:
        Rules:
          - Id: ExpireObjectsAfter1YearPROD
            Status: Enabled
            ExpirationInDays: 365
            Prefix: PROD/
          - Id: ExpireObjectsAfter1YearCODE
            Status: Enabled
            ExpirationInDays: 365
            Prefix: CODE/
