AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A Firehose transformation lambda for serialising the acquisitions event stream to csv

Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: support
  App:
    Description: Application name
    Type: String
    Default: acquisitions-firehose-transformer
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
    - CODE
    - PROD
  OphanRole:
    Type: String
    Description: ARN of the Ophan cross-account role
  DeployBucket:
    Description: Deploy bucket
    Type: String
    Default: membership-dist

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${App}-${Stage}
      Description: A Firehose transformation lambda for serialising the acquisitions event stream to csv
      Runtime: java11
      Handler: com.gu.acquisitionFirehoseTransformer.Lambda::handler
      MemorySize: 512
      Timeout: 300
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/${App}/${App}.jar
      Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
        - Effect: Allow
          Action: s3:GetObject
          Resource:
            - arn:aws:s3::*:membership-dist/*
      - Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Resource:
            Ref: OphanRole
      - Statement:
          Effect: Allow
          Action: dynamodb:*
          Resource:
            - !Sub arn:aws:dynamodb:*:${AWS::AccountId}:table/fixer-io-cache
            - !Sub arn:aws:dynamodb:*:${AWS::AccountId}:table/fixer-io-cache/index/*
