AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A Firehose transformation lambda for serialising the acquisitions event stream to csv

Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: support
  App:
    Description: Application name
    Type: String
    Default: acquisitions-firehose-transformer
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
    - CODE
    - PROD
  DeployBucket:
    Description: Deploy bucket
    Type: String
    Default: membership-dist

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${App}-${Stage}
      Description: A Firehose transformation lambda for serialising the acquisitions event stream to csv
      Runtime: java8
      Handler: com.gu.acquisitionFirehoseTransformer.Lambda::handler
      MemorySize: 256
      Timeout: 300
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/${App}/${App}.zip
      Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
        - Effect: Allow
          Action: s3:GetObject
          Resource:
            - arn:aws:s3::*:membership-dist/*

