AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda/API gateway for creating Stripe Setup Intents

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
    Default: CODE

Mappings:
  StageMap:
    CODE:
      StripeConfig: test
    PROD:
      StripeConfig: live
  Constants:
    Alarm:
      Process: Follow the process in https://docs.google.com/document/d/1_3El3cly9d7u_jPgTcRjLxmdG2e919zCLvmcFCLOYAk/edit
      Urgent: URGENT 9-5 -

Conditions:
  ProdOnlyResource: !Equals [!Ref Stage, PROD]

Resources:
  LambdaFunctionOverHttps:
    Type: AWS::Serverless::Function
    Properties:
      Description: Returns a stripe setup intent token so we can get authorisation of a recurring payment on the client side
      FunctionName:
        !Sub stripe-intent-${Stage}
      Handler: com.gu.stripeIntent.Handler::handleRequest
      CodeUri:
        Bucket: support-workers-dist
        Key: !Sub support/${Stage}/stripe-intent/stripe-intent.jar
      MemorySize: 2048
      Runtime: java21
      Timeout: 300
      Environment:
        Variables:
          Stage: !Ref Stage
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - lambda:InvokeFunction
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/stripe-intent-${Stage}:log-stream:*"
        - Statement:
          - Effect: Allow
            Action: s3:GetObject
            Resource:
              - !Sub
                - arn:aws:s3:::gu-reader-revenue-private/stripe/${stripeConfig}-stripe-regular.private.conf
                - stripeConfig:
                    !FindInMap [ StageMap, !Ref Stage, StripeConfig ]
  StripeIntentAlarm:
      Type: AWS::CloudWatch::Alarm
      Condition: ProdOnlyResource
      Properties:
        AlarmActions:
          - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alarms-handler-topic-${Stage}
        AlarmName: !Join
            - ' '
            - - !FindInMap [ Constants, Alarm, Urgent ]
              - 'PROD'
              - 'Stripe create setup intent Lambda failing'
        AlarmDescription: !Join
            - ' '
            - - 'Impact - Credit card checkout will not work for subscriptions or recurring contributions.'
              - !FindInMap [ Constants, Alarm, Process ]
        Namespace: AWS/Lambda
        MetricName: Errors
        Dimensions:
          - Name: FunctionName
            Value: !Ref LambdaFunctionOverHttps
        Statistic: Sum
        ComparisonOperator: GreaterThanThreshold
        Threshold: 0
        EvaluationPeriods: 1
        Period: 60
