name: Setup Node and Install Dependencies
description: Sets up Node, enables corepack, and installs dependencies with pnpm
runs:
  using: "composite"
  steps:
    - run: npm install --global corepack@0.31.0
      shell: bash

    - run: corepack enable
      shell: bash

    - name: Setup Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: ".tool-versions"

    - name: Install
      run: pnpm install
      shell: bash
