AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda for running the IT tests. Depends on the support workers deployment pushing out the JAR file.

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
    Default: CODE

Mappings:
  Constants:
    Alarm:
      Process: See the wiki at https://github.com/guardian/support-frontend/wiki/Automated-IT-Tests

Conditions:
  ProdOnlyResource: !Equals [!Ref Stage, PROD]

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Runs the IT tests
      FunctionName:
        !Sub support-it-tests-${Stage}
      Handler: com.gu.RunITTests::handleRequest
      CodeUri:
        Bucket: support-workers-dist
        Key: !Sub support/${Stage}/it-test-runner/it-test-runner.jar
      MemorySize: 2048
      Runtime: java21
      Timeout: 300
      Environment:
        Variables:
          Stage: !Ref Stage
      Events:
        RerunTests:
          Type: Schedule
          Properties:
            Schedule: 'rate(6 hours)'
            Description: run the tests regularly so we know if they're broken
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - lambda:InvokeFunction
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/it-tests-${Stage}:log-stream:*"
        - Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource: !Sub arn:aws:s3:::support-workers-dist/support/${Stage}/it-tests/support-workers-it.jar
        - Statement:
            - Effect: Allow
              Action: cloudwatch:PutMetricData
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource:
               - arn:aws:s3:::support-workers-private/CODE/support-workers.private.conf
               - arn:aws:s3:::gu-zuora-catalog/PROD/Zuora-CODE/catalog.json
               - arn:aws:s3:::gu-zuora-catalog/PROD/Zuora-PROD/catalog.json
        - Statement:
            - Effect: Allow
              Action: dynamodb:Scan
              Resource: arn:aws:dynamodb:*:*:table/MembershipSub-Promotions-CODE
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
                - sqs:GetQueueUrl
              Resource:
                Fn::ImportValue: !Sub "comms-CODE-EmailQueueArn"
        - Statement:
            - Effect: Allow
              Action: events:PutEvents
              Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/acquisitions-bus-CODE

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: LambdaFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/support-it-tests-${Stage}
      RetentionInDays: 90

  ITTestFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: ProdOnlyResource
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alarms-handler-topic-${Stage}
      AlarmName: !Join
        - ' '
        - - 'non urgent -'
          - 'IT Tests are failing'
      AlarmDescription: !Join
        - ' '
        - - 'Impact - There may be improperly tested code in PROD or CODE test data is broken.'
          - !FindInMap [ Constants, Alarm, Process ]
      Metrics:
        - Id: total
          Expression: "FILL(m1,0)"
          Label: ITTestsFailed
        - Id: m1
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: support-frontend
              MetricName: it-test-failed
              Dimensions:
                - Name: Stage
                  Value: !Ref Stage
            Stat: Sum
            Period: 900
            Unit: Count
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      EvaluationPeriods: 9
      DatapointsToAlarm: 3
      TreatMissingData: breaching

  ITTestNotRunningAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: ProdOnlyResource
    Properties:
      AlarmActions:
        - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:alarms-handler-topic-${Stage}
      AlarmName: !Join
        - ' '
        - - 'non urgent -'
          - 'IT Tests are not running'
      AlarmDescription: !Join
        - ' '
        - - 'Impact - we are not aware of integration test pass/fail status'
          - !FindInMap [ Constants, Alarm, Process ]
      Metrics:
        - Id: total
          Expression: "SUM([FILL(m1,0),FILL(m2,0)])"
          Label: ITTestsCount
        - Id: m1
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: support-frontend
              MetricName: it-test-succeeded
              Dimensions:
                - Name: Stage
                  Value: !Ref Stage
            Stat: Sum
            Period: 3600 # 1 hour
            Unit: Count
        - Id: m2
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: support-frontend
              MetricName: it-test-failed
              Dimensions:
                - Name: Stage
                  Value: !Ref Stage
            Stat: Sum
            Period: 3600 # 1 hour
            Unit: Count
      ComparisonOperator: LessThanThreshold
      Threshold: 100
      EvaluationPeriods: 7
      DatapointsToAlarm: 7
      TreatMissingData: breaching
