#!/bin/bash

# Exit if any of these commands fail
set -e

export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"  # This loads nvm

nvm install
nvm use

# Installing yarn
YARN_VERSION="1.22.5"
YARN_LOCATION="tools/${YARN_VERSION}"

if [ ! -d "$YARN_LOCATION" ]; then
	mkdir -p ${YARN_LOCATION}
	cd ${YARN_LOCATION}/
	wget -qO- https://github.com/yarnpkg/yarn/releases/download/v${YARN_VERSION}/yarn-v${YARN_VERSION}.tar.gz | tar zvx
	cd ../..
fi

# Installing packages via yarn

${YARN_LOCATION}/yarn-v$YARN_VERSION/bin/yarn install

# Building the html files used for Server Side Rendering
${YARN_LOCATION}/yarn-v$YARN_VERSION/bin/yarn run build-ssr

# Building the client-side assets
${YARN_LOCATION}/yarn-v$YARN_VERSION/bin/yarn run build-prod

