name: Bundle Analyser
on:
  push:
    branches:
      - main

jobs:
  build_check:
    if: github.repository_owner == 'guardian'
    name: Bundle Analyser
    defaults:
      run:
        working-directory: support-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Generate production build for github action
        run: pnpm build-github-action

      - name: Run Bundle Analyser
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bundle-analyser-report
          path: support-frontend/public/compiled-assets/webpack-stats.html
