name: Deploy Fastly Snippets
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
        required: true
      delete-snippets:
        type: boolean
        description: Delete all Fastly snippets before deploying
        required: true
        default: true
      lock-and-activate-service:
        type: boolean
        description: Lock and activate the service version after snippets are deployed
        required: true
        default: true
jobs:
  deploy_fastly_snippets:
    name: Deploy Fastly snippets [${{ github.event.inputs.environment }}]
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    env:
      FASTLY_SERVICE_ID: ${{ secrets.FASTLY_SERVICE_ID }}
      FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
      DELETE_SNIPPETS: ${{ github.event.inputs.delete-snippets }}
      LOCK_AND_ACTIVATE_SERVICE: ${{ github.event.inputs.lock-and-activate-service }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Deploy Fastly snippets
        run: node .github/workflows/deploy-fastly-snippets.js
