name: Lighthouse CI
on:
  push
  # workflow_dispatch:
  # pull_request:
  #   types: [labeled] # Only run when a PR is labeled with the 'Seen-on-PROD' label set by prout
jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - name: run Lighthouse CI
        run: |
          yarn global add @lhci/cli@0.14.x
          lhci autorun
