name: Build payment-api

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  GU_SUPPORT_WORKERS_LOAD_S3_CONFIG: false

jobs:
  payment_api_build:
    if: >-
      (github.actor != 'dependabot[bot]') &&
        (github.repository_owner == 'guardian' ||
          github.event_name == 'push')

    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read

    name: payment-api build
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env

      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Build CFN from CDK
        run: ./script/ci
        working-directory: cdk

      - name: Setup Scala
        uses: guardian/setup-scala@v1

      - name: Build deb package
        run: sbt "project support-payment-api" clean debian:packageBin

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v4.3.2
        with:
          projectName: support:payment-api-mono
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          buildNumberOffset: 6000
          commentingEnabled: 'false'
          configPath: ./support-payment-api/src/main/resources/riff-raff.yaml
          contentDirectories: |
            payment-api:
              - support-payment-api/target/payment-api_0.1_all.deb
            cfn:
              - cdk/cdk.out/Payment-API-CODE.template.json
              - cdk/cdk.out/Payment-API-PROD.template.json
