name: Update Dependency Graph for sbt
on:
  push:
    branches:
      - main
      - sbt-dependency-graph-228eca55167613ca
  workflow_dispatch:
jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4.2.1
      - name: Setup Scala
        uses: guardian/setup-scala@v1
      - name: Submit dependencies
        id: submit
        uses: scalacenter/sbt-dependency-submission@d84eef4c09e633bcf5f113bcad7fd5e9af1baee9 # v3.2.3
      - name: Log snapshot for user validation
        id: validate
        run: cat ${{ steps.submit.outputs.snapshot-json-path }} | jq
    permissions:
      contents: write
