name: Setup Node and Install Dependencies

on:
  workflow_call:

jobs:
  setup_node_and_install:
    runs-on: ubuntu-latest
    steps:
      - run: npm install --global corepack@0.31.0

      - run: corepack enable
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install
        run: pnpm install
