name: 'Close stale PRs'
on:
  schedule:
    # 10:00, Tuesday - Thursday
    # Avoids alerting people outside of working hours
    - cron: '0 10 * * 2-4'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          days-before-stale: 30
          stale-issue-message: 'This issue has been open and inactive for 30 days and marked as stale. It will close in 7 days if there is no further activity.'
          stale-pr-message: 'This PR has been open and inactive for 30 days and marked as stale. It will close in 7 days if there is no further activity.'
