name: Build supporter-product-data

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  supporter_product_data_build:
    if: >-
      (github.actor != 'dependabot[bot]') &&
        (github.repository_owner == 'guardian' ||
          github.event_name == 'push')

    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read

    name: supporter-product-data build
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env

      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: sbt/setup-sbt@v1

      - name: Setup Scala
        uses: guardian/setup-scala@v1

      - name: Build jar
        run:  sbt "project supporter-product-data" clean test assembly

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v4
        with:
          projectName: support:supporter-product-data
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          buildNumberOffset: 6000
          commentingEnabled: 'false'
          configPath: ./supporter-product-data/riff-raff.yaml
          contentDirectories: |
            cfn:
              - supporter-product-data/cloudformation/cfn.yaml
            supporter-product-data:
              - supporter-product-data/target/scala-2.13/supporter-product-data.jar