name: Build support-frontend

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  GU_SUPPORT_WORKERS_LOAD_S3_CONFIG: false

jobs:
  support_frontend_build:
    if: >-
      (github.actor != 'dependabot[bot]') &&
        (github.repository_owner == 'guardian' ||
          github.event_name == 'push')

    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read

    name: support-frontend build
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env

      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Build the html used for SSR pages
        run: pnpm --filter support-frontend build-ssr

      - name: Build assets
        run: pnpm --filter support-frontend build-prod

      - name: Build CFN from CDK
        run: ./script/ci
        working-directory: cdk

      - name: TypeScript support-backend test and build
        run: |
          pnpm --filter support-backend test
          pnpm --filter support-backend build
          pnpm --filter support-backend build-prod-node-modules
          pushd support-backend
          mv target_node_modules/node_modules ./target/
          tar -czf support-backend.tar.gz target
          popd

      - name: Setup Scala
        uses: guardian/setup-scala@v1

      - name: Build, test, and package
        run: sbt "project support-frontend" clean test debian:packageBin

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v4
        with:
          projectName: support:frontend-mono
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          buildNumberOffset: 10000
          commentingEnabled: 'false'
          configPath: ./support-frontend/conf/riff-raff.yaml
          contentDirectories: |
            frontend:
              - support-frontend/target/support-frontend_1.0-SNAPSHOT_all.deb
            support-backend:
              - support-backend/support-backend.tar.gz
            cfn-backend:
              - cdk/cdk.out/Backend-CODE.template.json
              - cdk/cdk.out/Backend-PROD.template.json
            cfn-frontend:
              - cdk/cdk.out/Frontend-CODE.template.json
              - cdk/cdk.out/Frontend-PROD.template.json
            assets-static:
              - support-frontend/public/compiled-assets