name: Build support-lambdas

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  support_lambdas_build:
    if: >-
      (github.actor != 'dependabot[bot]') &&
        (github.repository_owner == 'guardian' ||
          github.event_name == 'push')

    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read

    name: support-lambdas build
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env

      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Build CFN from CDK
        run: ./script/ci
        working-directory: cdk

      - name: Setup Scala
        uses: guardian/setup-scala@v1

      - name: Build jar
        run: |
          sbt "project support-lambdas" clean test assembly

      - name: Upload Acquisition Events API to Riff-Raff
        uses: guardian/actions-riff-raff@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          projectName: "support:lambdas:acquisition-events-api"
          buildNumberOffset: 15000
          configPath: ./support-lambdas/acquisition-events-api/riff-raff.yaml
          commentingEnabled: "false"
          contentDirectories: |
            acquisition-events-api:
              - ./support-lambdas/acquisition-events-api/target/scala-2.13/acquisition-events-api.jar
            cfn:
              - ./cdk/cdk.out/Acquisition-Events-API-CODE.template.json
              - ./cdk/cdk.out/Acquisition-Events-API-PROD.template.json

      - name: Upload Stripe Intent to Riff-Raff
        uses: guardian/actions-riff-raff@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          projectName: "support:lambdas:Stripe Intent"
          buildNumberOffset: 15000
          configPath: ./support-lambdas/stripe-intent/riff-raff.yaml
          commentingEnabled: "false"
          contentDirectories: |
            stripe-intent:
              - ./support-lambdas/stripe-intent/target/scala-2.13/stripe-intent.jar
            cfn:
              - ./support-lambdas/stripe-intent/cfn.yaml

  support_lambdas_typescripts_bigquery_acquisition_publisher:
    if: >-
      (github.actor != 'dependabot[bot]') &&
        (github.repository_owner == 'guardian' ||
          github.event_name == 'push')

    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read

    name: support-lambdas-bigquery-acquisition-publisher build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Build CFN from CDK
        run: ./script/ci
        working-directory: cdk

      - run: pnpm --filter bigquery-acquisitions-publisher tsc --noEmit

      - run: pnpm --filter bigquery-acquisitions-publisher prettier

      - run: pnpm --filter bigquery-acquisitions-publisher test

      - run: pnpm --filter bigquery-acquisitions-publisher build

      - run: zip -qr index.zip ./*.js
        working-directory: support-lambdas/bigquery-acquisitions-publisher/target/typescript

      - name: Upload to Riff-Raff
        uses: guardian/actions-riff-raff@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          projectName: "support:lambdas:bigquery-acquisitions-publisher"
          buildNumberOffset: 15000
          configPath: "support-lambdas/bigquery-acquisitions-publisher/riff-raff.yaml"
          commentingEnabled: "false"
          contentDirectories: |
            cfn:
              - ./cdk/cdk.out
            bigquery-acquisitions-publisher:
              - ./support-lambdas/bigquery-acquisitions-publisher/target/typescript/index.zip
